/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SearchPredicates = t.iface([], {
  "date": "Date",
  "test": "boolean",
});

const exportedTypeSuite: t.ITypeSuite = {
  SearchPredicates,
};
export default exportedTypeSuite;
